import { AppData, AgentIntel, IconData } from './types';

const icon = (emoji: string, bg?: string): IconData => ({ emoji, bg });

function intel(partial: Partial<AgentIntel> & Pick<AgentIntel, 'activeAgents' | 'totalAgents'>): AgentIntel {
  return {
    uptime: 0.97,
    throughput: 1240,
    intelligence: 0.82,
    memory: 0.64,
    expansion: 0.58,
    flow: [],
    brain: [],
    skills: [],
    strengths: [],
    weaknesses: [],
    improvements: [],
    notWorthIt: [],
    ...partial,
  };
}

const brainRegions = (intelligence: number, memory: number, expansion: number) => [
  { id: 'core', label: 'Núcleo', level: intelligence, x: 0.5, y: 0.5 },
  { id: 'mem', label: 'Memória', level: memory, x: 0.26, y: 0.38 },
  { id: 'exp', label: 'Expansão', level: expansion, x: 0.76, y: 0.36 },
  { id: 'lang', label: 'Linguagem', level: 0.71, x: 0.32, y: 0.7 },
  { id: 'plan', label: 'Planejamento', level: 0.66, x: 0.72, y: 0.68 },
  { id: 'percep', label: 'Percepção', level: 0.59, x: 0.5, y: 0.8 },
];

export const SEED: AppData = {
  messageCount: 59,
  settings: {
    voiceEnabled: true,
    voiceRate: 1.0,
    voicePitch: 1.0,
    alwaysOn: false,
    autoNarrate: true,
    userName: 'Maycon',
  },
  tasks: [
    {
      id: 'task_agents',
      title: 'Atualizar agentes de IA',
      note: 'Subir novos prompts e revisar skills ativas.',
      priority: 'urgent',
      done: false,
      icon: icon('🤖'),
      createdAt: 1,
    },
    {
      id: 'task_crm',
      title: 'Sincronizar dados do CRM',
      note: 'Integração com a base de clientes da Perfection.',
      priority: 'high',
      done: false,
      icon: icon('🔄'),
      createdAt: 2,
    },
  ],
  goals: [
    {
      id: 'goal_crm',
      title: 'Sincronizar dados do CRM',
      note: 'Pipeline de dados unificado.',
      priority: 'high',
      progress: 0.45,
      icon: icon('🔄'),
      createdAt: 1,
    },
    {
      id: 'goal_agents',
      title: 'Atualizar agentes de IA',
      note: 'Frota de agentes na versão mais recente.',
      priority: 'urgent',
      progress: 0.7,
      icon: icon('🧠'),
      createdAt: 2,
    },
  ],
  projects: [
    {
      id: 'proj_airsoft',
      name: 'Perfection Airsoft',
      description: 'Loja e operação de airsoft',
      icon: icon('🎯'),
      createdAt: 1,
      intel: intel({
        activeAgents: 4,
        totalAgents: 6,
        uptime: 0.98,
        throughput: 1860,
        intelligence: 0.86,
        memory: 0.72,
        expansion: 0.63,
        flow: [
          { id: 'f1', label: 'Catálogo importado', state: 'done' },
          { id: 'f2', label: 'CRM integrado', state: 'done' },
          { id: 'f3', label: 'Atendimento automático', state: 'active' },
          { id: 'f4', label: 'Campanhas de venda', state: 'next' },
          { id: 'f5', label: 'Previsão de estoque', state: 'next' },
        ],
        brain: brainRegions(0.86, 0.72, 0.63),
        skills: [
          { id: 's1', name: 'Atendimento', load: 0.82, active: true },
          { id: 's2', name: 'Vendas', load: 0.64, active: true },
          { id: 's3', name: 'Estoque', load: 0.41, active: true },
          { id: 's4', name: 'Pós-venda', load: 0.2, active: false },
        ],
        strengths: ['Atendimento 24/7 consistente', 'Conhece todo o catálogo', 'Conversão alta no WhatsApp'],
        weaknesses: ['Previsão de estoque imprecisa', 'Pouca memória de clientes antigos'],
        improvements: ['Conectar nota fiscal', 'Treinar com histórico de compras'],
        notWorthIt: ['Posts manuais diários', 'Relatórios em PDF que ninguém lê'],
      }),
    },
    {
      id: 'proj_barber',
      name: 'App Barber',
      description: 'Agendamento para barbearias',
      icon: icon('💈'),
      createdAt: 2,
      intel: intel({
        activeAgents: 2,
        totalAgents: 5,
        uptime: 0.94,
        throughput: 760,
        intelligence: 0.71,
        memory: 0.55,
        expansion: 0.48,
        flow: [
          { id: 'f1', label: 'Cadastro de barbeiros', state: 'done' },
          { id: 'f2', label: 'Agenda online', state: 'active' },
          { id: 'f3', label: 'Lembretes automáticos', state: 'next' },
          { id: 'f4', label: 'Pagamento no app', state: 'next' },
        ],
        brain: brainRegions(0.71, 0.55, 0.48),
        skills: [
          { id: 's1', name: 'Agendamento', load: 0.78, active: true },
          { id: 's2', name: 'Lembretes', load: 0.36, active: true },
          { id: 's3', name: 'Fidelidade', load: 0.18, active: false },
        ],
        strengths: ['Agenda nunca dá choque de horário', 'Onboarding rápido de barbeiros'],
        weaknesses: ['Sem cobrança integrada', 'Notificações genéricas'],
        improvements: ['Integrar Pix', 'Mensagens personalizadas por cliente'],
        notWorthIt: ['Programa de pontos complexo'],
      }),
    },
    {
      id: 'proj_beleza',
      name: 'App Beleza',
      description: 'Plataforma de beleza',
      icon: icon('💅'),
      createdAt: 3,
      intel: intel({
        activeAgents: 3,
        totalAgents: 7,
        uptime: 0.91,
        throughput: 540,
        intelligence: 0.68,
        memory: 0.49,
        expansion: 0.74,
        flow: [
          { id: 'f1', label: 'Marketplace inicial', state: 'done' },
          { id: 'f2', label: 'Perfis de profissionais', state: 'active' },
          { id: 'f3', label: 'Recomendação por IA', state: 'next' },
          { id: 'f4', label: 'Expansão regional', state: 'next' },
        ],
        brain: brainRegions(0.68, 0.49, 0.74),
        skills: [
          { id: 's1', name: 'Descoberta', load: 0.7, active: true },
          { id: 's2', name: 'Recomendação', load: 0.52, active: true },
          { id: 's3', name: 'Marketing', load: 0.44, active: true },
          { id: 's4', name: 'Suporte', load: 0.12, active: false },
        ],
        strengths: ['Crescimento acelerado', 'Boa descoberta de profissionais'],
        weaknesses: ['Memória de preferências fraca', 'Uptime abaixo da meta'],
        improvements: ['Estabilizar infraestrutura', 'Memória de longo prazo por usuária'],
        notWorthIt: ['Anúncios pagos sem segmentação'],
      }),
    },
  ],
};
